### ISSUE TITLE
Create the generator

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs-travis#1]
This generator should be used to produce a `.travis.yml` that is used for running tests in CI like described here in the [pmo guide](https://donejs.com/place-my-order.html#setting-up-travis-ci).

The basic configuration file looks like:

```
language: node_js
node_js: node
addons:
  firefox: "latest"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
```

Do we need to do anything different in the generator other than writing this file out? Should browsers or anything else be configurable? Perhaps a different Firefox version?

This generator will run with:

```
donejs add travis
```

**Comment by matthewp** [comment]
Also this should add a badge to the readme like:

```md
[![Build Status](https://travis-ci.org/<your-username>/place-my-order.png?branch=master)](https://travis-ci.org/<your-username>/place-my-order)
```

**Comment by m-mujica** [comment]
What should we do if there is a `.travis.yml` in the project already? should we try and merge our defaults or bail out?

**Comment by matthewp** [comment]
I would say bailout.
